

spring.datasource.url=jdbc:postgresql://dpg-d7n32f77f7vs73fhdr9g-a
spring.datasource.username=auth_user
spring.datasource.password=29gXbvD8hpzlb2b5tJvbZiTxVpE1nJ9g

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET:my-secret-key}

server.port=${PORT:8080}